name: Maven Build

on:
  push:
    branches: [ "main", "feature" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: numeric-app
        path: target/numeric-*.jar
